# Copyright (c) 2007-2018 Carnegie Mellon University. All Rights Reserved. See COPYRIGHT file for details.

source 'https://rubygems.org'

gem 'rails', '~>3.2.12'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3', '~>1.3.5'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.2'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer'
  gem 'execjs'

  gem 'uglifier', '>= 1.0.3'
end

#gem 'jquery-rails', ">=2.2.1","<= 2.3.0"
gem 'jquery-rails'

# User authentication

# gem 'devise'

gem 'annotate'

gem "best_in_place", '= 3.0.2'

#gem 'kaminari'

gem 'populator'

gem 'will_paginate', '= 3.0.5'

gem 'thin'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

# To create/export zip files
gem 'rubyzip', '=1.2.1'
gem 'zip-zip'
