# -*- coding: utf-8 -*-

# <legal>
# SCALe version r.6.2.2.2.A
# 
# Copyright 2020 Carnegie Mellon University.
# 
# NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING
# INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON
# UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR
# IMPLIED, AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF
# FITNESS FOR PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS
# OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT
# MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM PATENT,
# TRADEMARK, OR COPYRIGHT INFRINGEMENT.
# 
# Released under a MIT (SEI)-style license, please see COPYRIGHT file or
# contact permission@sei.cmu.edu for full terms.
# 
# [DISTRIBUTION STATEMENT A] This material has been approved for public
# release and unlimited distribution.  Please see Copyright notice for
# non-US Government use and distribution.
# 
# DM19-1274
# </legal>

development:
  scale: 'scale:8083'
  datahub: 'datahub:8084'
  stats: 'stats:8086'
  priority: 'priority:8085'
  registration: 'registration:8087'
  pulsar: 'pulsar:6650'

test:
  scale: 'scale:8083'
  datahub: 'datahub:8084'
  stats: 'stats:8086'
  priority: 'priority:8085'
  registration: 'registration:8087'
  pulsar: 'pulsar:6650'
  automation:
    # this is used by both python and ruby to create an account
    # for automated testing
    account:
      name: "automation00"
      password: "autopass00"
      first_name: "Auto"
      last_name: "Mation"
