# <legal>
# SCALe version r.6.7.0.0.A
# 
# Copyright 2021 Carnegie Mellon University.
# 
# NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING
# INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON
# UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR
# IMPLIED, AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF
# FITNESS FOR PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS
# OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT
# MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM PATENT,
# TRADEMARK, OR COPYRIGHT INFRINGEMENT.
# 
# Released under a MIT (SEI)-style license, please see COPYRIGHT file or
# contact permission@sei.cmu.edu for full terms.
# 
# [DISTRIBUTION STATEMENT A] This material has been approved for public
# release and unlimited distribution.  Please see Copyright notice for
# non-US Government use and distribution.
# 
# DM19-1274
# </legal>

source 'https://rubygems.org'

gem 'rails', '~>5.2'
gem 'responders', '~>2.4.0'
gem 'sqlite3', '~>1.3.5'

### TEST START

gem 'pry'
gem 'pry-nav'

gem 'rubocop'
gem 'jshint'
gem 'minitest', group: :test
gem 'minitest-reporters', group: :test

group :test do
gem 'simplecov', '~> 0.12.0'
end

### TEST END

#gem 'turbolinks', '~> 2.5.3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sprockets-rails', :require => 'sprockets/railtie'
  gem 'bootstrap-sass', '3.3.7'
  gem 'will_paginate-bootstrap', '~> 1.0', '>= 1.0.1'
  #gem 'sass', '~> 3.5.5'
  gem 'coffee-rails'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer'
  gem 'execjs'
  gem 'uglifier', '~> 4.1.4'
end

group :development do
	#for thin client
	gem 'listen'
end

gem 'jquery-rails', '~> 4.3.1'
gem 'jquery-ui-rails', '~> 6.0.1'

# User authentication

# gem 'devise'

gem 'annotate'

gem 'best_in_place', '= 3.1.1'

gem 'rake', '~> 12.3.0' #needed to run SSL unit tests
#gem 'heroku'

#gem 'kaminari'

gem 'populator'

gem 'will_paginate', '= 3.1.6' #for splitting alert table rows across pages


gem 'thin', '~> 1.7.2' #needed for running SCALe (bundle exec thin start --port [port_num])

# To use ActiveModel has_secure_password
gem 'bcrypt'


#gem 'protected_attributes_continued' #needed for deprecated method attr_accessible

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To create/export zip files
gem 'rubyzip', '=1.3'
gem 'zip-zip'

# For manipulating git repositories
gem 'git'

#see config/boot.rb
gem 'bootsnap'

gem 'rest-client'

gem 'webmock'

gem 'rails-controller-testing'

# needed for openapi_client
gem 'typhoeus', '~> 1.0', '>= 1.0.1'
