# coding: utf-8
# <legal>
# SCALe version r.6.7.0.0.A
# 
# Copyright 2021 Carnegie Mellon University.
# 
# NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING
# INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON
# UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR
# IMPLIED, AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF
# FITNESS FOR PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS
# OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT
# MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM PATENT,
# TRADEMARK, OR COPYRIGHT INFRINGEMENT.
# 
# Released under a MIT (SEI)-style license, please see COPYRIGHT file or
# contact permission@sei.cmu.edu for full terms.
# 
# [DISTRIBUTION STATEMENT A] This material has been approved for public
# release and unlimited distribution.  Please see Copyright notice for
# non-US Government use and distribution.
# 
# DM19-1274
# </legal>

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RequestToken(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, request_id: str=None, message: str=None):  # noqa: E501
        """RequestToken - a model defined in Swagger

        :param request_id: The request_id of this RequestToken.  # noqa: E501
        :type request_id: str
        :param message: The message of this RequestToken.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'request_id': str,
            'message': str
        }

        self.attribute_map = {
            'request_id': 'request_id',
            'message': 'message'
        }
        self._request_id = request_id
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'RequestToken':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The request_token of this RequestToken.  # noqa: E501
        :rtype: RequestToken
        """
        return util.deserialize_model(dikt, cls)

    @property
    def request_id(self) -> str:
        """Gets the request_id of this RequestToken.

        Id used to correlate messages with each other  # noqa: E501

        :return: The request_id of this RequestToken.
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id: str):
        """Sets the request_id of this RequestToken.

        Id used to correlate messages with each other  # noqa: E501

        :param request_id: The request_id of this RequestToken.
        :type request_id: str
        """
        if request_id is None:
            raise ValueError("Invalid value for `request_id`, must not be `None`")  # noqa: E501

        self._request_id = request_id

    @property
    def message(self) -> str:
        """Gets the message of this RequestToken.


        :return: The message of this RequestToken.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this RequestToken.


        :param message: The message of this RequestToken.
        :type message: str
        """

        self._message = message
