# Client code for the SCAIFE Statistics Module
#
# This is the auto-generated client code for the SCAIFE Stats Module,
# which facilitates auditing static analysis alerts using classifiers,
# optional adaptive heuristics (active learning), and meta-alert
# prioritization. SCAIFE enables jump-starting labeled datasets using
# test suites. It is intended to enable a wide range of users (with
# widely varying datasets, static analysis tools, machine learning
# expertise, and amount of labeled data) to benefit from using
# classifiers and sophisticated prioritization to automatically triage
# static analysis meta-alerts.
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.0.1
#
# <legal>
# SCALe version r.6.7.0.0.A
# 
# Copyright 2021 Carnegie Mellon University.
# 
# NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING
# INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON
# UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR
# IMPLIED, AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF
# FITNESS FOR PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS
# OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT
# MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM PATENT,
# TRADEMARK, OR COPYRIGHT INFRINGEMENT.
# 
# Released under a MIT (SEI)-style license, please see COPYRIGHT file or
# contact permission@sei.cmu.edu for full terms.
# 
# [DISTRIBUTION STATEMENT A] This material has been approved for public
# release and unlimited distribution.  Please see Copyright notice for
# non-US Government use and distribution.
# 
# DM19-1274
# </legal>

# Common files
require_relative 'statistics/api_client'
require_relative 'statistics/api_error'
require_relative 'statistics/version'
require_relative 'statistics/configuration'

# Models
require_relative 'statistics/models/alert'
require_relative 'statistics/models/alert_updates_response'
require_relative 'statistics/models/analysis_results'
require_relative 'statistics/models/checker_mappings'
require_relative 'statistics/models/classifier_instance'
require_relative 'statistics/models/classifier_instance_data'
require_relative 'statistics/models/classifier_results'
require_relative 'statistics/models/classifier_results_probability_data'
require_relative 'statistics/models/close_adaptive_heuristics_response'
require_relative 'statistics/models/condition'
require_relative 'statistics/models/create_classifier_response'
require_relative 'statistics/models/determination'
require_relative 'statistics/models/determination_dangerous_construct_list'
require_relative 'statistics/models/determination_dead_list'
require_relative 'statistics/models/determination_flag_list'
require_relative 'statistics/models/determination_ignored_list'
require_relative 'statistics/models/determination_inapplicable_environment_list'
require_relative 'statistics/models/determination_notes_list'
require_relative 'statistics/models/determination_verdict_list'
require_relative 'statistics/models/list_classifiers_response'
require_relative 'statistics/models/list_classifiers_response_adaptive_heuristics'
require_relative 'statistics/models/list_classifiers_response_ahpos'
require_relative 'statistics/models/message'
require_relative 'statistics/models/meta_alert'
require_relative 'statistics/models/multiple_alerts'
require_relative 'statistics/models/packages_with_tool_data'
require_relative 'statistics/models/packages_with_tool_data_tool_data'
require_relative 'statistics/models/secondary_message'
require_relative 'statistics/models/secondary_message_all_of'
require_relative 'statistics/models/source_mappings'
require_relative 'statistics/models/source_file'
require_relative 'statistics/models/source_function'
require_relative 'statistics/models/taxonomy'

# APIs
require_relative 'statistics/api/data_hub_to_stats_api'
require_relative 'statistics/api/stats_server_api'
require_relative 'statistics/api/uito_stats_api'

module Scaife
module Api
module Statistics

  class << self
    # Customize default settings for the SDK using block.
    #   Scaife::Api::Statistics.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end

end
end
end
