# Client code for the SCAIFE Datahub Module
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.0.1
#
# <legal>
# SCALe version r.6.7.0.0.A
# 
# Copyright 2021 Carnegie Mellon University.
# 
# NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING
# INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON
# UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR
# IMPLIED, AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF
# FITNESS FOR PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS
# OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT
# MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM PATENT,
# TRADEMARK, OR COPYRIGHT INFRINGEMENT.
# 
# Released under a MIT (SEI)-style license, please see COPYRIGHT file or
# contact permission@sei.cmu.edu for full terms.
# 
# [DISTRIBUTION STATEMENT A] This material has been approved for public
# release and unlimited distribution.  Please see Copyright notice for
# non-US Government use and distribution.
# 
# DM19-1274
# </legal>

require 'date'
require 'time'

module Scaife
module Api
module Datahub

  class MetaAlertWId
    # Condition ID associated with a Taxonomy
    attr_accessor :condition_id

    # Checker ID associated with a Tool
    attr_accessor :checker_id

    attr_accessor :filepath

    attr_accessor :line_number

    attr_accessor :ui_meta_alert_id

    attr_accessor :alert_ids

    attr_accessor :determination

    attr_accessor :auto_verdict

    attr_accessor :meta_alert_id

    attr_accessor :ct_pm_verdict

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'condition_id' => :'condition_id',
        :'checker_id' => :'checker_id',
        :'filepath' => :'filepath',
        :'line_number' => :'line_number',
        :'ui_meta_alert_id' => :'ui_meta_alert_id',
        :'alert_ids' => :'alert_ids',
        :'determination' => :'determination',
        :'auto_verdict' => :'auto_verdict',
        :'meta_alert_id' => :'meta_alert_id',
        :'ct_pm_verdict' => :'ct_pm_verdict'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'condition_id' => :'String',
        :'checker_id' => :'String',
        :'filepath' => :'String',
        :'line_number' => :'Integer',
        :'ui_meta_alert_id' => :'String',
        :'alert_ids' => :'Array<String>',
        :'determination' => :'Determination',
        :'auto_verdict' => :'Hash<String, String>',
        :'meta_alert_id' => :'String',
        :'ct_pm_verdict' => :'Hash<String, String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'MetaAlertNoId',
      :'MetaAlertWIdAllOf'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Scaife::Api::Datahub::MetaAlertWId` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Scaife::Api::Datahub::MetaAlertWId`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'condition_id')
        self.condition_id = attributes[:'condition_id']
      end

      if attributes.key?(:'checker_id')
        self.checker_id = attributes[:'checker_id']
      end

      if attributes.key?(:'filepath')
        self.filepath = attributes[:'filepath']
      end

      if attributes.key?(:'line_number')
        self.line_number = attributes[:'line_number']
      end

      if attributes.key?(:'ui_meta_alert_id')
        self.ui_meta_alert_id = attributes[:'ui_meta_alert_id']
      end

      if attributes.key?(:'alert_ids')
        if (value = attributes[:'alert_ids']).is_a?(Array)
          self.alert_ids = value
        end
      end

      if attributes.key?(:'determination')
        self.determination = attributes[:'determination']
      end

      if attributes.key?(:'auto_verdict')
        if (value = attributes[:'auto_verdict']).is_a?(Hash)
          self.auto_verdict = value
        end
      end

      if attributes.key?(:'meta_alert_id')
        self.meta_alert_id = attributes[:'meta_alert_id']
      end

      if attributes.key?(:'ct_pm_verdict')
        if (value = attributes[:'ct_pm_verdict']).is_a?(Hash)
          self.ct_pm_verdict = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @filepath.nil?
        invalid_properties.push('invalid value for "filepath", filepath cannot be nil.')
      end

      if @line_number.nil?
        invalid_properties.push('invalid value for "line_number", line_number cannot be nil.')
      end

      if @alert_ids.nil?
        invalid_properties.push('invalid value for "alert_ids", alert_ids cannot be nil.')
      end

      if @meta_alert_id.nil?
        invalid_properties.push('invalid value for "meta_alert_id", meta_alert_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @filepath.nil?
      return false if @line_number.nil?
      return false if @alert_ids.nil?
      return false if @meta_alert_id.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          condition_id == o.condition_id &&
          checker_id == o.checker_id &&
          filepath == o.filepath &&
          line_number == o.line_number &&
          ui_meta_alert_id == o.ui_meta_alert_id &&
          alert_ids == o.alert_ids &&
          determination == o.determination &&
          auto_verdict == o.auto_verdict &&
          meta_alert_id == o.meta_alert_id &&
          ct_pm_verdict == o.ct_pm_verdict
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [condition_id, checker_id, filepath, line_number, ui_meta_alert_id, alert_ids, determination, auto_verdict, meta_alert_id, ct_pm_verdict].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Scaife::Api::Datahub.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
end
end
