# Client code for the SCAIFE Datahub Module
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 5.0.1
#
# <legal>
# SCALe version r.6.7.0.0.A
# 
# Copyright 2021 Carnegie Mellon University.
# 
# NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING
# INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON
# UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR
# IMPLIED, AS TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF
# FITNESS FOR PURPOSE OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS
# OBTAINED FROM USE OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT
# MAKE ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM PATENT,
# TRADEMARK, OR COPYRIGHT INFRINGEMENT.
# 
# Released under a MIT (SEI)-style license, please see COPYRIGHT file or
# contact permission@sei.cmu.edu for full terms.
# 
# [DISTRIBUTION STATEMENT A] This material has been approved for public
# release and unlimited distribution.  Please see Copyright notice for
# non-US Government use and distribution.
# 
# DM19-1274
# </legal>

require 'date'
require 'time'

module Scaife
module Api
module Datahub

  class PackageMetadata
    attr_accessor :package_name

    attr_accessor :package_description

    attr_accessor :author_source

    attr_accessor :code_language_ids

    # URL to Source Code Archive
    attr_accessor :code_source_url

    attr_accessor :source_file_url

    attr_accessor :source_function_url

    # Test Suite Associated with this Package
    attr_accessor :test_suite_id

    attr_accessor :alerts

    # ID of the tools used with this Package
    attr_accessor :tool_ids

    attr_accessor :ci_enabled

    # url to git repository
    attr_accessor :git_url

    # User name of git user to clone repository (Read-only access)
    attr_accessor :git_user

    # Access token for git user
    attr_accessor :git_access_token

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'package_name' => :'package_name',
        :'package_description' => :'package_description',
        :'author_source' => :'author_source',
        :'code_language_ids' => :'code_language_ids',
        :'code_source_url' => :'code_source_url',
        :'source_file_url' => :'source_file_url',
        :'source_function_url' => :'source_function_url',
        :'test_suite_id' => :'test_suite_id',
        :'alerts' => :'alerts',
        :'tool_ids' => :'tool_ids',
        :'ci_enabled' => :'ci_enabled',
        :'git_url' => :'git_url',
        :'git_user' => :'git_user',
        :'git_access_token' => :'git_access_token'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'package_name' => :'String',
        :'package_description' => :'String',
        :'author_source' => :'String',
        :'code_language_ids' => :'Array<String>',
        :'code_source_url' => :'String',
        :'source_file_url' => :'String',
        :'source_function_url' => :'String',
        :'test_suite_id' => :'String',
        :'alerts' => :'Array<AlertWUiId>',
        :'tool_ids' => :'Array<String>',
        :'ci_enabled' => :'Boolean',
        :'git_url' => :'String',
        :'git_user' => :'String',
        :'git_access_token' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Scaife::Api::Datahub::PackageMetadata` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Scaife::Api::Datahub::PackageMetadata`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'package_name')
        self.package_name = attributes[:'package_name']
      end

      if attributes.key?(:'package_description')
        self.package_description = attributes[:'package_description']
      end

      if attributes.key?(:'author_source')
        self.author_source = attributes[:'author_source']
      end

      if attributes.key?(:'code_language_ids')
        if (value = attributes[:'code_language_ids']).is_a?(Array)
          self.code_language_ids = value
        end
      end

      if attributes.key?(:'code_source_url')
        self.code_source_url = attributes[:'code_source_url']
      end

      if attributes.key?(:'source_file_url')
        self.source_file_url = attributes[:'source_file_url']
      end

      if attributes.key?(:'source_function_url')
        self.source_function_url = attributes[:'source_function_url']
      end

      if attributes.key?(:'test_suite_id')
        self.test_suite_id = attributes[:'test_suite_id']
      end

      if attributes.key?(:'alerts')
        if (value = attributes[:'alerts']).is_a?(Array)
          self.alerts = value
        end
      end

      if attributes.key?(:'tool_ids')
        if (value = attributes[:'tool_ids']).is_a?(Array)
          self.tool_ids = value
        end
      end

      if attributes.key?(:'ci_enabled')
        self.ci_enabled = attributes[:'ci_enabled']
      end

      if attributes.key?(:'git_url')
        self.git_url = attributes[:'git_url']
      end

      if attributes.key?(:'git_user')
        self.git_user = attributes[:'git_user']
      end

      if attributes.key?(:'git_access_token')
        self.git_access_token = attributes[:'git_access_token']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @package_name.nil?
        invalid_properties.push('invalid value for "package_name", package_name cannot be nil.')
      end

      if @package_description.nil?
        invalid_properties.push('invalid value for "package_description", package_description cannot be nil.')
      end

      if @code_language_ids.nil?
        invalid_properties.push('invalid value for "code_language_ids", code_language_ids cannot be nil.')
      end

      if @tool_ids.nil?
        invalid_properties.push('invalid value for "tool_ids", tool_ids cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @package_name.nil?
      return false if @package_description.nil?
      return false if @code_language_ids.nil?
      return false if @tool_ids.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          package_name == o.package_name &&
          package_description == o.package_description &&
          author_source == o.author_source &&
          code_language_ids == o.code_language_ids &&
          code_source_url == o.code_source_url &&
          source_file_url == o.source_file_url &&
          source_function_url == o.source_function_url &&
          test_suite_id == o.test_suite_id &&
          alerts == o.alerts &&
          tool_ids == o.tool_ids &&
          ci_enabled == o.ci_enabled &&
          git_url == o.git_url &&
          git_user == o.git_user &&
          git_access_token == o.git_access_token
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [package_name, package_description, author_source, code_language_ids, code_source_url, source_file_url, source_function_url, test_suite_id, alerts, tool_ids, ci_enabled, git_url, git_user, git_access_token].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Scaife::Api::Datahub.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
end
end
